import type { Metadata } from "next";
import Link from "next/link";
import Navbar from "../../components/Navbar";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "The terms that govern your use of RouteAlpha.",
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="px-6 py-12 lg:px-8">
        <article className="mx-auto max-w-3xl rounded-[2rem] border border-white/70 bg-white/85 p-8 shadow-[0_24px_80px_-42px_rgba(15,23,42,0.32)] backdrop-blur-sm sm:p-12">
          <p className="text-sm font-semibold uppercase tracking-[0.24em] text-teal-700">
            Legal
          </p>
          <h1 className="mt-4 text-4xl font-semibold tracking-tight text-slate-950">
            Terms of Service
          </h1>
          <p className="mt-2 text-sm text-slate-500">Last updated: July 4, 2026</p>

          <div className="mt-8 space-y-8 text-base leading-7 text-slate-600">
            <section>
              <h2 className="text-xl font-semibold text-slate-950">
                Acceptance of terms
              </h2>
              <p className="mt-3">
                By creating an account or using RouteAlpha, you agree to these
                terms. If you are using the service on behalf of a company, you
                represent that you have authority to bind that company.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-950">
                The service
              </h2>
              <p className="mt-3">
                RouteAlpha routes AI inference requests across model providers
                and reports cost, latency, and routing analytics. Model
                responses are generated by third-party providers, and we do not
                guarantee their accuracy. Cost figures shown in the product are
                estimates, not invoices.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-950">
                Acceptable use
              </h2>
              <p className="mt-3">
                You agree not to misuse the service, including attempting to
                gain unauthorized access, disrupting the platform, submitting
                unlawful content through the playground, or reselling access
                without our written permission.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-950">
                Accounts
              </h2>
              <p className="mt-3">
                You are responsible for safeguarding your account credentials
                and for activity that occurs under your account. We may suspend
                accounts that violate these terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-950">
                Disclaimer and limitation of liability
              </h2>
              <p className="mt-3">
                The service is provided &quot;as is&quot; without warranties of
                any kind. To the maximum extent permitted by law, RouteAlpha is
                not liable for indirect, incidental, or consequential damages
                arising from your use of the service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-950">
                Changes to these terms
              </h2>
              <p className="mt-3">
                We may update these terms from time to time. Continued use of
                the service after changes take effect constitutes acceptance of
                the updated terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-slate-950">Contact</h2>
              <p className="mt-3">
                Questions about these terms? Reach us through the{" "}
                <Link href="/contact" className="font-medium text-teal-700 underline hover:text-teal-800">
                  contact page
                </Link>
                .
              </p>
            </section>
          </div>
        </article>
      </main>
    </>
  );
}
